# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 5.4 #3
controller_patience: 5.3

planner_frequency: 10.0
planner_patience: 10.0

oscillation_timeout: 10.0  #10
oscillation_distance: 3  #2

clearing_rotation_allowed: false
