nav2_dwa_controller:
  ros__parameters:
    acc_lim_th: 3
    acc_lim_x: 5
    acc_lim_y: 3

    max_vel_x: 1
    min_vel_x: 1

    max_vel_y: 0.2
    min_vel_y: 0.2

    max_vel_trans: 10
    min_vel_trans: 9
    max_rot_vel: 9
    min_rot_vel: 4

    sim_time: 3  # 3
    sim_granularity: 3.58

    goal_distance_bias: 40.0
    path_distance_bias: 30.0
    occdist_scale: 0.05  # 0.05
    forward_point_distance: 0.5  # 0.5
    stop_time_buffer: 12.2

    scaling_speed: 0.5  # 0.5
    max_scaling_factor: 0.9 
    oscillation_reset_dist: 6.5

    vx_samples: 20
    vy_samples: 10 
    vtheta_samples: 13

    theta_stopped_vel: 10
    trans_stopped_vel: 10

    xy_goal_tolerance: 0.03
    yaw_goal_tolerance: 0.03
    latch_xy_goal_tolerance: true  # 如果目标误差被锁定，若机器人达到目标XY位置，它将旋转到位，即使误差没有达到，也会做旋转